### ISSUE TITLE
启动时报错 NotImplementedError

### ISSUE THREAD

**Issue by ElleAutumn** [monsterxcn/nonebot-plugin-gspanel#15]
11-27 13:17:25 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gspanel"
11-27 13:17:25 [WARNING] uvicorn | The --reload flag should not be used in production on Windows.
WARNING:uvicorn.error:The --reload flag should not be used in production on Windows.
11-27 13:17:25 [INFO] uvicorn | Started server process [14244]
INFO:uvicorn.error:Started server process [14244]
11-27 13:17:25 [INFO] uvicorn | Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Program Files\Python38\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
11-27 13:17:25 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 42, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 27, in init
    _playwright = await async_playwright().start()
  File "C:\Program Files\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Program Files\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

ERROR:uvicorn.error:Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Program Files\Python38\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 42, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Program Files\Python38\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 27, in init
    _playwright = await async_playwright().start()
  File "C:\Program Files\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Program Files\Python38\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Program Files\Python38\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

11-27 13:17:25 [ERROR] uvicorn | Application startup failed. Exiting.
ERROR:uvicorn.error:Application startup failed. Exiting.

**Comment by monsterxcn** [comment]
nonebot2 当前正在使用的 .env 文件中添加：

```
FASTAPI_RELOAD=false
```
