### ISSUE TITLE
提瓦特小助手接口无法访问

### ISSUE THREAD

**Issue by Kiana1314** [monsterxcn/nonebot-plugin-gspanel#22]
```
12-28 11:40:57 [ERROR] nonebot_plugin_gspanel | 提瓦特小助手接口无法访问或返回错误
Traceback (most recent call last):
  File "C:\bot\NB2\venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\bot\NB2\venv\lib\site-packages\anyio\streams\tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "C:\bot\NB2\venv\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\bot\NB2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "C:\bot\NB2\venv\lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\bot\NB2\venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\bot\NB2\nb\.\nonebot-plugin-gspanel\nonebot_plugin_gspanel\data_source.py", line 80, in queryDamageApi
    res = await client.post(
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1848, in post
    return await self.request(
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\bot\NB2\venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

12-28 11:40:57 [ERROR] nonebot_plugin_gspanel | UID160507172 的 4 位角色队伍伤害计算请求失败！
>>>> [提瓦特返回] {}
```

**Comment by monsterxcn** [comment]
呃呃，你不会以为提瓦特小助手这个小程序是我做的吧（

我认为这个报错提示已经写的够明白了
