### ISSUE TITLE
raise NotImplementedError

### ISSUE THREAD

**Issue by Chanpoe** [monsterxcn/nonebot-plugin-gspanel#30]
环境：Python 3.10.6
报错描述：导入插件后显示如下错误，尝试换成python3.8版本，发现python3.8版本无法成功导入nonebot_plugin_htmlrender，请问该如何解决呢？

02-02 01:26:40 [INFO] uvicorn | Waiting for application startup.
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at D:\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:217> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 224, in run
    await self._transport.connect()
  File "D:\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 139, in connect
    raise exc
  File "D:\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
02-02 01:26:40 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\Python\Python310\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "D:\Python\Python310\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "D:\Python\Python310\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "D:\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 60, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "D:\Python\Python310\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 36, in init
    _playwright = await async_playwright().start()
  File "D:\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "D:\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "D:\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\Python\Python310\lib\asyncio\base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by monsterxcn** [comment]
#15 #18
