### ISSUE TITLE
Failed to import "nonebot_plugin_htmlrender"

### ISSUE THREAD

**Issue by Chanpoe** [monsterxcn/nonebot-plugin-gspanel#36]
环境：Ubuntu 20.04
Python：Python 3.8.10
问题描述：去年12月的版本的gspanel想着更新一下，更新完提示以下报错（可能与我自己重新安装ChromeDriver有关）

```
02-10 21:39:42 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"                                                     
Traceback (most recent call last):                                                                                                
  File "/usr/local/bin/nb", line 8, in <module>                                                                                   
    sys.exit(main())                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__                                             
    return self.main(*args, **kwargs)                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main                                                 
    rv = self.invoke(ctx)                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke                                               
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                       
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke                                               
    return ctx.invoke(self.callback, **ctx.params)                                                                                
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke                                                
    return __callback(*args, **kwargs)                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run                                          
    run_bot(file, app)                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 19, in run_bot                                    
    module = importlib.import_module(module_name)                                                                                 
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                     
    return _bootstrap._gcd_import(name[level:], package, level)                                                                   
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                      
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                               
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                               
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/ChanpoeBot/./bot.py", line 45, in <module>                                                                          
    nonebot.load_from_toml("pyproject.toml")                                                                                      
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(                 
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)                                                                                        
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)                                                                   
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                 
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                               
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                               
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)                                                                                                   
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                         
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                    
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/__init__.py", line 10, in <module>                          
    from .data_updater import updateCache                                                                                         
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                               
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                               
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/data_updater.py", line 12, in <module>
    from .data_source import queryDamageApi                                                                                       
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                               
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                               
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/data_source.py", line 21, in <module>
    require("nonebot_plugin_htmlrender")                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 165, in require
    plugin = load_plugin(name)                                   
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)                                                                                       
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)                                                                                        
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)                                                                   
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                             
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                              
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                               
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 233, in exec_module                                     super().exec_module(module)                    
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                           
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                      
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_htmlrender/__init__.py", line 4, in <module>
    from .browser import get_browser, get_new_page, shutdown_browser                                                                
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_htmlrender/browser.py", line 18, in <module>                          
    from playwright.async_api import Page, Error, Browser, Playwright, async_playwright                 
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/__init__.py", line 25, in <module>                                  import playwright.async_api._generated                                                                      
  File "/usr/local/lib/python3.8/dist-packages/playwright/async_api/_generated.py", line 25, in <module>                            
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl                                                  
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_accessibility.py", line 17, in <module>                            
    from playwright._impl._connection import Channel                                                                                
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 24, in <module>                               
    from pyee import EventEmitter                                                                                                     File "/usr/local/lib/python3.8/dist-packages/pyee/__init__.py", line 120, in <module>                                                 from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa                               
  File "/usr/local/lib/python3.8/dist-packages/pyee/trio.py", line 7, in <module>
    import trio
  File "/usr/local/lib/python3.8/dist-packages/trio/__init__.py", line 76, in <module>                                              
    from ._dtls import DTLSEndpoint, DTLSChannel                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/trio/_dtls.py", line 136, in <module>                                                
    @attr.frozen                 
AttributeError: module 'attr' has no attribute 'frozen'                                                                             
02-10 21:39:42 [ERROR] nonebot | Failed to import "nonebot_plugin_gspanel"                                                          
Traceback (most recent call last):                                
  File "/usr/local/bin/nb", line 8, in <module>                                                                                     
    sys.exit(main())                                              
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__                                               
    return self.main(*args, **kwargs)                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main                                                   
    rv = self.invoke(ctx)                                         
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke                                                 
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                         
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke                                                 
    return ctx.invoke(self.callback, **ctx.params)                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke                                                  
    return __callback(*args, **kwargs)                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run                                            
    run_bot(file, app)                                            
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 19, in run_bot                                      
    module = importlib.import_module(module_name)                                                                                   
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                       
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                   
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                 
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                        
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                 
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                           
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                      
  File "/root/ChanpoeBot/./bot.py", line 45, in <module>                                                                            
    nonebot.load_from_toml("pyproject.toml")                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 122, in load_from_toml                                 
    return load_all_plugins(plugins, plugin_dirs)                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 59, in load_all_plugins                                
    return manager.load_all_plugins()                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins                            
    return set(                  
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 169, in <genexpr>                                   
    filter(None, (self.load_plugin(name) for name in self.available_plugins))                                                       
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 141, in load_plugin                                 
    module = importlib.import_module(name)                                                                                          
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                                     
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                   
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                 
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                        
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                 
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)                                   
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                           
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                      
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/__init__.py", line 10, in <module>                            
    from .data_updater import updateCache                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/data_updater.py", line 12, in <module>                        
    from .data_source import queryDamageApi                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_gspanel/data_source.py", line 21, in <module>                         
    require("nonebot_plugin_htmlrender")                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 167, in require                                        
    raise RuntimeError(f'Cannot load plugin "{name}"!')                                                                             
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!
```

**Comment by Chanpoe** [comment]
附图，有代码高亮可能看着更清晰
![image](https://user-images.githubusercontent.com/84487466/218109027-53a290dd-12fe-4ae1-b87e-4cb681f72d12.png)

**Comment by monsterxcn** [comment]
试试这个？你这报错我也没见过，感觉是什么依赖版本不对。

```bash
pip install attr --upgrade
```

**Comment by monsterxcn** [comment]
或者也可能是 Python 3.8.10 也已经被淘汰了（我问 ChatGPT 他给我的第一条建议就是将 Python 升级至 3.9 以上 💦💦

**Comment by Chanpoe** [comment]
解决了，重新安装了一遍 22.2.0版本的attr
pip install attrs==22.2.0

**Comment by monsterxcn** [comment]
https://github.com/python-trio/trio/pull/2499

看了下这个，要用 `@frozen` 应该保证 attrs 版本不低于 20.1.0

解决方案：

```bash
pip install -U trio
```

**Comment by Chanpoe** [comment]
> 

感谢感谢！
