### ISSUE TITLE
查询角色报错 jinja2.exceptions.TemplateNotFound: panel-0.2.20.html

### ISSUE THREAD

**Issue by NanakoOfficial** [monsterxcn/nonebot-plugin-gspanel#40]
### 运行环境

 - 操作系统：Windows 10
 - Python 版本：3.8.5
 - NoneBot2 版本：2.0.0b5
 - GsPanel 版本：0.2.20
 - 其他环境版本：无

#### 场景

 - 触发命令： 面板
 - 命令输入：雷电将军
 - Bot 返回：无

#### 日志

```
02-18 20:23:37 [ERROR] nonebot | Running matcher <Matcher from src.plugins.nonebot_plugin_gspanel, type=message, priority=13, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\IRONY-Bot-main\IRONY-Bot\src\plugins\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\Desktop\0\software\IRONY-Bot-main\IRONY-Bot\src\plugins\nonebot_plugin_gspanel\__init__.py", line 51, in panel_handle
    rt = await getPanel(uid, char)
  File "D:\Desktop\0\software\IRONY-Bot-main\IRONY-Bot\src\plugins\nonebot_plugin_gspanel\data_source.py", line 277, in getPanel
    return await template_to_pic(
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_htmlrender\data_source.py", line 231, in template_to_pic
    template = template_env.get_template(template_name)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: panel-0.2.20.html
```

**Comment by monsterxcn** [comment]
红豆泥私密马赛！搓代码笔误了

麻烦稍后再更新一下 0.2.21 版本

**Comment by forchannot** [comment]
> 红豆泥私密马赛！搓代码笔误了
> 
> 麻烦稍后再更新一下 0.2.21 版本
似乎还是有问题，队伍伤害命令
![image](https://user-images.githubusercontent.com/100580891/219872863-ee9fc09c-a46f-4cb1-8779-a5e2475c1216.png)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\fwq\LittlePaimon\bot.py", line 41, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line
80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_gspanel\__init__.py", line 79, in team_handle
    rt = await getTeam(uid, chars, showDetail)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_gspanel\data_source.py", line 361, in getTeam
    return await template_to_pic(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_plugin_htmlrender\data_source.py", line 231, in template_to_pic
    template = template_env.get_template(template_name)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: team-0.2.20.html

**Comment by forchannot** [comment]
我看了下，队伍伤害应该也是team-0.2.7.html或者team-0.2.5.html吧

**Comment by monsterxcn** [comment]
忘记改下载了，真好，又水一个版本号（

急用可以先手动下载这两个文件：

 - https://cdn.monsterx.cn/bot/gspanel/team-0.2.20.html
 - https://cdn.monsterx.cn/bot/gspanel/team-0.2.20.css

**Comment by monsterxcn** [comment]
@forchannot 正常，需要 team-0.2.20.html 这个模板才会不显示那个表格，没这个当然还是按旧的模板来
